# Write your sentences here. The format of this file should be key: value,
# where a key is a language you know or skill that you have, and the value
# is a sentence or two describing your ability.
python: I love Python!
